# Generated by Django 3.1.3 on 2020-12-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Admin'), (1, 'Lekarz'), (2, 'Praktykant')], default=0, verbose_name='rola'),
        ),
    ]
