# Generated by Django 3.1.3 on 2021-03-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Admin'), (1, 'Lekarz'), (2, 'Praktykant')], default=0, verbose_name='rola'),
        ),
    ]
