# Generated by Django 3.1.3 on 2021-03-08 18:17

from django.db import migrations


def prepopulate(apps, sechema_editor):
    Morphology = apps.get_model("morphologies", "Morphology")
    Morphology.objects.bulk_create([
        Morphology(name="WBC", unit="G/l", norm_min=4.0, norm_max=11.0),
        Morphology(name="Neurocyty", unit="G/l", norm_min=2.0, norm_max=7.5),
        Morphology(name="Limfocyty", unit="G/l", norm_min=1.5, norm_max=4.5),
        Morphology(name="Eozynofile", unit="G/l", norm_min=0.04, norm_max=0.4),
        Morphology(name="RBC", unit="T/l", norm_min=4.5, norm_max=6.5),
        Morphology(name="HGB", unit="g/dl", norm_min=13.0, norm_max=18.0),
        Morphology(name="PLT", unit="G/l", norm_min=150.0, norm_max=400.0),
        Morphology(name="ALT", unit="U/l", norm_min=0.0, norm_max=41.0),
        Morphology(name="AST", unit="U/l", norm_min=0.0, norm_max=40.0),
        Morphology(name="ALP", unit="U/l", norm_min=40.0, norm_max=130.0),
        Morphology(name="GGTP", unit="U/l", norm_min=0.0, norm_max=71.0),
        Morphology(name="Glukoza", unit="mg/dl", norm_min=70.0, norm_max=99.0),
        Morphology(name="Kreatynina", unit="mg/dl", norm_min=0.7, norm_max=1.2),
        Morphology(name="CRP", unit="mg/l", norm_min=0.0, norm_max=5.0),
        Morphology(name="Żelazo w surowicy", unit="mcg/dl", norm_min=59.0, norm_max=158.0),
        Morphology(name="Ferrytyna", unit="ng/ml", norm_min=22.0, norm_max=275.0),
        Morphology(name="Cholesterol", unit="mg/dl", norm_min=115.0, norm_max=190.0),
        Morphology(name="LDL cholesterol", unit="mg/dl", norm_min=0.0, norm_max=115.0),
        Morphology(name="Trójglicerydy", unit="mg/dl", norm_min=0.0, norm_max=150.0),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('morphologies', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(prepopulate),
    ]
