# Generated by Django 3.1.3 on 2021-03-14 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210223_2324'),
        ('morphologies', '0002_prepopulate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='morphologyexamination',
            options={'verbose_name': 'Wynik morfologii', 'verbose_name_plural': 'Wyniki morfologii'},
        ),
        migrations.AlterField(
            model_name='morphologyexamination',
            name='examination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='morphologies', to='core.examination', verbose_name='Badanie'),
        ),
    ]
