# Generated by Django 3.1.3 on 2021-09-23 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('morphologies', '0003_auto_20210314_2048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='morphology',
            options={'verbose_name': 'Badanie laboratoryjne', 'verbose_name_plural': 'Badania laboratoryjne'},
        ),
        migrations.AlterModelOptions(
            name='morphologyexamination',
            options={'verbose_name': 'Wynik badania laboratoryjnego', 'verbose_name_plural': 'Wyniki badań laboratoryjnych'},
        ),
        migrations.AlterField(
            model_name='morphologyexamination',
            name='morphology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='morphologies.morphology', verbose_name='Badanie laboratoryjne'),
        ),
    ]
