# Generated by Django 3.1.3 on 2021-02-13 00:14

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='kraj')),
                ('date_start', models.DateField(verbose_name='początek')),
                ('date_end', models.DateField(verbose_name='koniec')),
                ('food', models.PositiveSmallIntegerField(choices=[(0, 'restauracje'), (1, 'lokalne'), (2, 'własne'), (3, 'mieszane')], null=True, verbose_name='odżywianie')),
                ('drinks', models.PositiveSmallIntegerField(choices=[(0, 'butelkowane'), (1, 'lokalne'), (2, 'strumienie'), (3, 'mieszane')], null=True, verbose_name='napoje')),
                ('visit', models.PositiveSmallIntegerField(choices=[(0, 'zawodowy'), (1, 'turystyczny')], null=True, verbose_name='rodzaj wizyty')),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.examination')),
            ],
            options={
                'verbose_name': 'podróż',
                'verbose_name_plural': 'podróże',
            },
        ),
    ]
