# Generated by Django 3.1.3 on 2020-11-08 23:34

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='days',
        ),
        migrations.AddField(
            model_name='travel',
            name='country',
            field=django_countries.fields.CountryField(default='PL', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travel',
            name='date_end',
            field=models.DateField(default='2020-01-01', verbose_name='koniec'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travel',
            name='date_start',
            field=models.DateField(default='2020-01-01', verbose_name='początek'),
            preserve_default=False,
        ),
    ]
