# Generated by Django 3.1.3 on 2021-06-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0003_auto_20210308_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='visit',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'zawodowy'), (1, 'turystyczny'), (2, 'do bliskich')], null=True, verbose_name='rodzaj wizyty'),
        ),
    ]
