# Generated by Django 3.1.3 on 2021-06-14 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0004_auto_20210612_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='specialist_advise',
            field=models.BooleanField(null=True, verbose_name='korzystanie z porady specjalistycznej'),
        ),
        migrations.AddField(
            model_name='travel',
            name='specificity',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'swoista'), (1, 'nieswoista')], null=True, verbose_name='stosowanie profilaktyki'),
        ),
    ]
