# Generated by Django 3.1.3 on 2021-06-14 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0005_auto_20210614_0331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travel',
            old_name='specialist_advise',
            new_name='specialist_advice',
        ),
    ]
