# Generated by Django 3.1.3 on 2021-06-14 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0006_auto_20210614_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='specialist_advice',
            field=models.BooleanField(null=True, verbose_name='Porada specjalistycznej'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='specificity',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'swoista'), (1, 'nieswoista')], null=True, verbose_name='Profilaktyka'),
        ),
    ]
