# Generated by Django 3.1.3 on 2021-07-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0007_auto_20210614_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='specialist_advice',
            field=models.BooleanField(null=True, verbose_name='Porada specjalistyczna'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='visit',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'zawodowy'), (1, 'turystyczny'), (2, 'do bliskich')], null=True, verbose_name='rodzaj pobytu'),
        ),
    ]
