# Generated by Django 3.1.3 on 2021-02-13 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('afflictions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='imię')),
                ('last_name', models.CharField(max_length=200, verbose_name='nazwisko')),
                ('education', models.PositiveSmallIntegerField(choices=[(0, 'brak'), (1, 'podstawowe'), (2, 'średnie'), (3, 'wyższe')], verbose_name='wykształcenie')),
                ('gender', models.PositiveSmallIntegerField(choices=[(1, 'mężczyzna'), (2, 'kobieta'), (3, 'inna')], verbose_name='płeć')),
            ],
            options={
                'verbose_name': 'pacjent',
                'verbose_name_plural': 'pacjenci',
            },
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='data')),
                ('note', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Notatka')),
                ('collagen_layer_thickening', models.BooleanField(blank=True, null=True, verbose_name='pogrubienie warstwy kolagenu u podstawy komórek nabłonka')),
                ('increased_intraepithelial_lymphocytes', models.BooleanField(blank=True, null=True, verbose_name='zwiększona liczba limfocytów śródnabłonkowych')),
                ('lymphocytes_infiltration', models.BooleanField(blank=True, null=True, verbose_name='naciek z limfocytów')),
                ('plasmocytes_infiltration', models.BooleanField(blank=True, null=True, verbose_name='naciek z plazmocytów')),
                ('eosinophils_infiltration', models.BooleanField(blank=True, null=True, verbose_name='naciek z eozynofili')),
                ('mast_cells_infiltration', models.BooleanField(blank=True, null=True, verbose_name='naciek z komórek tucznych')),
                ('neutrocytes_infiltration', models.BooleanField(blank=True, null=True, verbose_name='naciek z neutrocytów')),
                ('afflictions', models.ManyToManyField(blank=True, related_name='examinations', to='afflictions.Affliction', verbose_name='objawy')),
                ('parasites', models.ManyToManyField(blank=True, related_name='examinations', to='afflictions.Parasite', verbose_name='pasożyty')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.patient', verbose_name='pacjent')),
            ],
            options={
                'verbose_name': ('Badanie',),
                'verbose_name_plural': 'Badania',
            },
        ),
    ]
