# Generated by Django 3.1.3 on 2020-11-08 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(verbose_name='imię')),
                ('last_name', models.TextField(verbose_name='nazwisko')),
                ('education', models.PositiveSmallIntegerField(choices=[(0, 'brak'), (1, 'podstawowe'), (2, 'średnie'), (3, 'wyższe')], verbose_name='wykształcenie')),
                ('gender', models.PositiveSmallIntegerField(choices=[(1, 'mężczyzna'), (2, 'kobieta'), (3, 'inna')], verbose_name='płeć')),
            ],
            options={
                'verbose_name': 'pacjent',
                'verbose_name_plural': 'pacjenci',
            },
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='data')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.patient', verbose_name='pacjent')),
            ],
            options={
                'verbose_name': ('Badanie',),
                'verbose_name_plural': 'Badania',
            },
        ),
    ]
