# Generated by Django 3.1.3 on 2020-11-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_remove_animal_examinations'),
        ('core', '0002_auto_20201108_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='animals',
            field=models.ManyToManyField(related_name='examinations', through='animals.AnimalExamination', to='animals.Animal'),
        ),
    ]
