# Generated by Django 3.1.3 on 2021-02-23 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210218_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.PositiveSmallIntegerField(verbose_name='wiek'),
        ),
    ]
