# Generated by Django 3.1.3 on 2021-04-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210223_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(0, 'mężczyzna'), (1, 'kobieta'), (2, 'inna')], verbose_name='płeć'),
        ),
    ]
