# Generated by Django 3.1.3 on 2020-11-08 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afflictions', '0001_initial'),
        ('core', '0003_examination_animals'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='afflictions',
            field=models.ManyToManyField(related_name='examinations', to='afflictions.Affliction'),
        ),
        migrations.AddField(
            model_name='examination',
            name='sicknesses',
            field=models.ManyToManyField(related_name='examinations', through='afflictions.SicknessExamination', to='afflictions.Sickness'),
        ),
    ]
