# Generated by Django 3.1.3 on 2020-11-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afflictions', '0003_auto_20201109_2034'),
        ('core', '0004_auto_20201109_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='fungi',
            field=models.ManyToManyField(related_name='examinations', through='afflictions.FungusExamination', to='afflictions.Fungus'),
        ),
        migrations.AddField(
            model_name='examination',
            name='parasites',
            field=models.ManyToManyField(related_name='examinations', to='afflictions.Parasite'),
        ),
    ]
