# Generated by Django 3.1.3 on 2021-06-14 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_examination_viruses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examination',
            name='collagen_layer_thickening',
        ),
        migrations.RemoveField(
            model_name='examination',
            name='eosinophils_infiltration',
        ),
        migrations.RemoveField(
            model_name='examination',
            name='increased_intraepithelial_lymphocytes',
        ),
        migrations.RemoveField(
            model_name='examination',
            name='lymphocytes_infiltration',
        ),
        migrations.RemoveField(
            model_name='examination',
            name='mast_cells_infiltration',
        ),
        migrations.RemoveField(
            model_name='examination',
            name='neutrocytes_infiltration',
        ),
        migrations.RemoveField(
            model_name='examination',
            name='plasmocytes_infiltration',
        ),
    ]
