# Generated by Django 3.1.3 on 2020-11-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afflictions', '0004_auto_20201109_2109'),
        ('core', '0005_auto_20201109_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='collagen_layer_thickening',
            field=models.BooleanField(blank=True, null=True, verbose_name='pogrubienie warstwy kolagenu u podstawy komórek nabłonka'),
        ),
        migrations.AddField(
            model_name='examination',
            name='eosinophils_infiltration',
            field=models.BooleanField(blank=True, null=True, verbose_name='naciek z eozynofili'),
        ),
        migrations.AddField(
            model_name='examination',
            name='increased_intraepithelial_lymphocytes',
            field=models.BooleanField(blank=True, null=True, verbose_name='zwiększona liczba limfocytów śródnabłonkowych'),
        ),
        migrations.AddField(
            model_name='examination',
            name='lymphocytes_infiltration',
            field=models.BooleanField(blank=True, null=True, verbose_name='naciek z limfocytów'),
        ),
        migrations.AddField(
            model_name='examination',
            name='mast_cells_infiltration',
            field=models.BooleanField(blank=True, null=True, verbose_name='naciek z komórek tucznych'),
        ),
        migrations.AddField(
            model_name='examination',
            name='neutrocytes_infiltration',
            field=models.BooleanField(blank=True, null=True, verbose_name='naciek z neutrocytów'),
        ),
        migrations.AddField(
            model_name='examination',
            name='plasmocytes_infiltration',
            field=models.BooleanField(blank=True, null=True, verbose_name='naciek z plazmocytów'),
        ),
        migrations.AlterField(
            model_name='examination',
            name='afflictions',
            field=models.ManyToManyField(blank=True, related_name='examinations', to='afflictions.Affliction'),
        ),
        migrations.AlterField(
            model_name='examination',
            name='parasites',
            field=models.ManyToManyField(blank=True, related_name='examinations', to='afflictions.Parasite'),
        ),
    ]
