# Generated by Django 3.1.3 on 2021-06-14 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210614_0346'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='collagen_layer_thickening',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'brak'), (1, 'mało'), (2, 'umiarkowany'), (3, 'intensywnie')], null=True, verbose_name='pogrubienie warstwy kolagenu u podstawy komórek nabłonka'),
        ),
        migrations.AddField(
            model_name='examination',
            name='eosinophils_infiltration',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'brak'), (1, 'mało'), (2, 'umiarkowany'), (3, 'intensywnie')], null=True, verbose_name='naciek z eozynofili'),
        ),
        migrations.AddField(
            model_name='examination',
            name='increased_intraepithelial_lymphocytes',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'brak'), (1, 'mało'), (2, 'umiarkowany'), (3, 'intensywnie')], null=True, verbose_name='zwiększona liczba limfocytów śródnabłonkowych'),
        ),
        migrations.AddField(
            model_name='examination',
            name='lymphocytes_infiltration',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'brak'), (1, 'mało'), (2, 'umiarkowany'), (3, 'intensywnie')], null=True, verbose_name='naciek z limfocytów'),
        ),
        migrations.AddField(
            model_name='examination',
            name='mast_cells_infiltration',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'brak'), (1, 'mało'), (2, 'umiarkowany'), (3, 'intensywnie')], null=True, verbose_name='naciek z komórek tucznych'),
        ),
        migrations.AddField(
            model_name='examination',
            name='neutrocytes_infiltration',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'brak'), (1, 'mało'), (2, 'umiarkowany'), (3, 'intensywnie')], null=True, verbose_name='naciek z neutrocytów'),
        ),
        migrations.AddField(
            model_name='examination',
            name='plasmocytes_infiltration',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'brak'), (1, 'mało'), (2, 'umiarkowany'), (3, 'intensywnie')], null=True, verbose_name='naciek z plazmocytów'),
        ),
    ]
