# Generated by Django 3.1.3 on 2020-12-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afflictions', '0005_medicineexamination'),
        ('core', '0007_auto_20201213_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='medicines',
            field=models.ManyToManyField(related_name='examinations', through='afflictions.MedicineExamination', to='afflictions.Medicine'),
        ),
        migrations.AlterField(
            model_name='examination',
            name='afflictions',
            field=models.ManyToManyField(related_name='examinations', to='afflictions.Affliction', verbose_name='objawy'),
        ),
        migrations.AlterField(
            model_name='examination',
            name='parasites',
            field=models.ManyToManyField(related_name='examinations', to='afflictions.Parasite', verbose_name='pasożyty'),
        ),
    ]
