# Generated by Django 3.1.3 on 2021-07-20 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210614_0346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examination',
            options={'verbose_name': ('Wywiad medyczny / Badanie',), 'verbose_name_plural': 'Wywiady medyczne / Badania'},
        ),
    ]
