# Generated by Django 3.1.3 on 2021-07-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afflictions', '0015_vaccine'),
        ('core', '0008_auto_20210720_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='vaccines',
            field=models.ManyToManyField(blank=True, related_name='examinations', to='afflictions.Vaccine', verbose_name='szczepienia'),
        ),
    ]
