# Generated by Django 3.1.3 on 2021-09-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_examination_vaccines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examination',
            name='patient',
        ),
        migrations.AddField(
            model_name='examination',
            name='patient_age',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='wiek pacjenta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examination',
            name='patient_education',
            field=models.PositiveSmallIntegerField(choices=[(0, 'brak'), (1, 'podstawowe'), (2, 'średnie'), (3, 'wyższe')], default=1, verbose_name='wykształcenie pacjenta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examination',
            name='patient_gender',
            field=models.PositiveSmallIntegerField(choices=[(0, 'mężczyzna'), (1, 'kobieta'), (2, 'inna')], default=1, verbose_name='płeć pacjenta'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
