# Generated by Django 3.1.3 on 2020-11-08 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_auto_20201108_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='examinations',
        ),
    ]
