# Generated by Django 3.1.3 on 2020-11-08 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_remove_animal_examinations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animalexamination',
            options={'verbose_name': 'Kontakt ze zwierzęciem', 'verbose_name_plural': 'Kontakty ze zwierzętami'},
        ),
        migrations.AlterField(
            model_name='animalexamination',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.animal', verbose_name='zwierzę'),
        ),
    ]
