# Generated by Django 3.1.3 on 2020-11-08 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_examination_animals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affliction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nazwa')),
            ],
            options={
                'verbose_name': 'objaw',
                'verbose_name_plural': 'objawy',
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nazwa')),
            ],
            options={
                'verbose_name': ('lek',),
                'verbose_name_plural': 'leki',
            },
        ),
        migrations.CreateModel(
            name='Sickness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nazwa')),
                ('afflictions', models.ManyToManyField(related_name='sicknesses', to='afflictions.Affliction')),
            ],
            options={
                'verbose_name': ('choroba',),
                'verbose_name_plural': 'choroby',
            },
        ),
        migrations.CreateModel(
            name='SicknessExamination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antibiotics', models.BooleanField(blank=True, null=True, verbose_name='Antybiotyko terapia')),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.examination')),
                ('sickness', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='afflictions.sickness')),
            ],
        ),
    ]
