# Generated by Django 3.1.3 on 2021-02-13 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affliction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nazwa')),
            ],
            options={
                'verbose_name': 'objaw',
                'verbose_name_plural': 'objawy',
            },
        ),
        migrations.CreateModel(
            name='Fungus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('molecular_identification', models.TextField(verbose_name='identyfikacja molekularna')),
                ('antibiotics_resistance', models.PositiveSmallIntegerField(choices=[(0, 'niska'), (1, 'średnia'), (2, 'wysoka')], verbose_name='odporność na antybiotyki')),
            ],
            options={
                'verbose_name': 'grzyb',
                'verbose_name_plural': 'grzyby',
            },
        ),
        migrations.CreateModel(
            name='FungusExamination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='ilość <#TODO: jaka jednostka?>')),
            ],
            options={
                'verbose_name': 'grzyb w badaniu',
                'verbose_name_plural': 'grzyby w badaniu',
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nazwa')),
            ],
            options={
                'verbose_name': ('lek',),
                'verbose_name_plural': 'leki',
            },
        ),
        migrations.CreateModel(
            name='MedicineExamination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='ilość')),
                ('unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='jednostka')),
            ],
        ),
        migrations.CreateModel(
            name='Parasite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nazwa')),
            ],
            options={
                'verbose_name': 'pasożyt',
                'verbose_name_plural': 'pasożyty',
            },
        ),
        migrations.CreateModel(
            name='Sickness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nazwa')),
            ],
            options={
                'verbose_name': ('choroba',),
                'verbose_name_plural': 'choroby',
            },
        ),
        migrations.CreateModel(
            name='SicknessExamination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antibiotics', models.BooleanField(blank=True, null=True, verbose_name='Antybiotyko terapia')),
            ],
            options={
                'verbose_name': 'Choroba w badaniu',
                'verbose_name_plural': 'Choroby w badaniu',
            },
        ),
    ]
