# Generated by Django 3.1.3 on 2020-11-08 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afflictions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sickness',
            name='afflictions',
            field=models.ManyToManyField(related_name='sicknesses', to='afflictions.Affliction', verbose_name='objawy'),
        ),
    ]
