# Generated by Django 3.1.3 on 2021-02-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afflictions', '0002_auto_20210213_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fungus',
            name='afflictions',
            field=models.ManyToManyField(blank=True, null=True, related_name='fungi', to='afflictions.Affliction', verbose_name='objawy'),
        ),
    ]
