# Generated by Django 3.1.3 on 2020-11-09 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afflictions', '0003_auto_20201109_2034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fungus',
            options={'verbose_name': 'grzyb', 'verbose_name_plural': 'grzyby'},
        ),
        migrations.AlterModelOptions(
            name='fungusexamination',
            options={'verbose_name': 'grzyb w badaniu', 'verbose_name_plural': 'grzyby w badaniu'},
        ),
        migrations.AlterModelOptions(
            name='parasite',
            options={'verbose_name': 'pasożyt', 'verbose_name_plural': 'pasożyty'},
        ),
    ]
