# Generated by Django 3.1.3 on 2021-03-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afflictions', '0004_auto_20210314_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fungus',
            name='name',
            field=models.TextField(verbose_name='Nazwa'),
        ),
    ]
