# Generated by Django 3.1.3 on 2021-04-22 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afflictions', '0006_auto_20210314_2051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parasite',
            old_name='name',
            new_name='species',
        ),
    ]
