# Generated by Django 3.1.3 on 2021-06-12 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210422_1004'),
        ('afflictions', '0009_auto_20210612_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bacteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa')),
            ],
            options={
                'verbose_name': 'bakteria',
                'verbose_name_plural': 'bakterie',
            },
        ),
        migrations.AlterField(
            model_name='fungusexamination',
            name='high_resistance',
            field=models.ManyToManyField(related_name='examinations_fungi_high_resistance', to='afflictions.Medicine', verbose_name='oporny na'),
        ),
        migrations.AlterField(
            model_name='fungusexamination',
            name='low_resistance',
            field=models.ManyToManyField(related_name='examinations_fungi_low_resistance', to='afflictions.Medicine', verbose_name='wrażliwy na'),
        ),
        migrations.AlterField(
            model_name='fungusexamination',
            name='mid_resistance',
            field=models.ManyToManyField(related_name='examinations_fungi_mid_resistance', to='afflictions.Medicine', verbose_name='średnio wrażliwy na'),
        ),
        migrations.CreateModel(
            name='BacteriaExamination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bacteria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='examinations', to='afflictions.bacteria', verbose_name='bakteria')),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bacteria', to='core.examination', verbose_name='badanie')),
                ('high_resistance', models.ManyToManyField(related_name='examination_bacteria_high_resistance', to='afflictions.Medicine', verbose_name='oporny na')),
                ('low_resistance', models.ManyToManyField(related_name='examination_bacteria_low_resistance', to='afflictions.Medicine', verbose_name='wrażliwy na')),
                ('mid_resistance', models.ManyToManyField(related_name='examination_bacteria_mid_resistance', to='afflictions.Medicine', verbose_name='średnio wrażliwy na')),
            ],
            options={
                'verbose_name': 'grzyb w badaniu',
                'verbose_name_plural': 'grzyby w badaniu',
            },
        ),
    ]
