# Generated by Django 3.1.3 on 2021-06-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afflictions', '0010_auto_20210612_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bacteriaexamination',
            name='high_resistance',
            field=models.ManyToManyField(blank=True, related_name='examination_bacteria_high_resistance', to='afflictions.Medicine', verbose_name='oporny na'),
        ),
        migrations.AlterField(
            model_name='bacteriaexamination',
            name='low_resistance',
            field=models.ManyToManyField(blank=True, related_name='examination_bacteria_low_resistance', to='afflictions.Medicine', verbose_name='wrażliwy na'),
        ),
        migrations.AlterField(
            model_name='bacteriaexamination',
            name='mid_resistance',
            field=models.ManyToManyField(blank=True, related_name='examination_bacteria_mid_resistance', to='afflictions.Medicine', verbose_name='średnio wrażliwy na'),
        ),
        migrations.AlterField(
            model_name='fungusexamination',
            name='high_resistance',
            field=models.ManyToManyField(blank=True, related_name='examinations_fungi_high_resistance', to='afflictions.Medicine', verbose_name='oporny na'),
        ),
        migrations.AlterField(
            model_name='fungusexamination',
            name='low_resistance',
            field=models.ManyToManyField(blank=True, related_name='examinations_fungi_low_resistance', to='afflictions.Medicine', verbose_name='wrażliwy na'),
        ),
        migrations.AlterField(
            model_name='fungusexamination',
            name='mid_resistance',
            field=models.ManyToManyField(blank=True, related_name='examinations_fungi_mid_resistance', to='afflictions.Medicine', verbose_name='średnio wrażliwy na'),
        ),
    ]
