# Generated by Django 3.1.3 on 2021-06-14 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afflictions', '0012_auto_20210614_0252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicineexamination',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='medicineexamination',
            name='unit',
        ),
        migrations.AddField(
            model_name='medicineexamination',
            name='intake_time',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Czas przyjmowania'),
        ),
        migrations.AlterField(
            model_name='virus',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Gatunek'),
        ),
    ]
