# Generated by Django 3.1.3 on 2021-06-14 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afflictions', '0013_auto_20210614_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineexamination',
            name='intake_time',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Czas przyjmowania (tygodnie)'),
        ),
    ]
