# Generated by Django 3.1.3 on 2021-07-20 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afflictions', '0014_auto_20210614_0331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sickness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afflictions.sickness', unique=True, verbose_name='choroba')),
            ],
            options={
                'verbose_name': 'szczepionka',
                'verbose_name_plural': 'szpionki',
            },
        ),
    ]
